### ISSUE TITLE
🐞Errors using SNMP v2c to enrich the flow data

### ISSUE THREAD

**Issue by indigo423** [Riptide-Labs/riptide#66]
I've configured the container stack to use SNMP v2c to enrich lows with the interface data like this:

```yaml
 environment:
      RIPTIDE_ELASTIC_URL: http://elastic-01.labmonkeys.tech:9200
      RIPTIDE_ENRICHER_HOSTNAME_ENABLE: true
      RIPTIDE_SNMP_CONFIG_DEFINITIONS_0__SUBNET-ADDRESS: 192.168.8.0/21
      RIPTIDE_SNMP_CONFIG_DEFINITIONS_0__SNMP-VERSION: v2c
      RIPTIDE_SNMP_CONFIG_DEFINITIONS_0__COMMUNITY: public
```
After a while, I'm seeing the following exceptions in standard out of the running container:

```
riptide_1  | Caused by: com.fasterxml.jackson.databind.JsonMappingException: duplicate element: 0.0.0.0 (through reference chain: org.riptide.repository.elastic.doc.FlowDocument["hosts"])
riptide_1  | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3303) ~[jackson-databind-2.15.3.jar:2.15.3]
riptide_1  | 	at co.elastic.clients.json.jackson.JacksonJsonpMapper.serialize(JacksonJsonpMapper.java:98) ~[elasticsearch-java-8.10.4.jar:na]
riptide_1  | 	... 12 common frames omitted
riptide_1  | Caused by: java.lang.IllegalArgumentException: duplicate element: 0.0.0.0
riptide_1  | 	at java.base/java.util.ImmutableCollections$Set12.<init>(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.Set.of(Unknown Source) ~[na:na]
riptide_1  | 	at org.riptide.repository.elastic.doc.FlowDocument.getHosts(FlowDocument.java:287) ~[classes/:na]
^Criptide_1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[na:na]
canceled
```

A packet capture from the SNMP shows a weird thing, it has version 1 and uses a bulk get which isn't supported with v1. Not sure if that is related.

```json
  {
    "_index": "packets-2023-11-25",
    "_type": "doc",
    "_score": null,
    "_source": {
      "layers": {
        "frame": {
          "frame.interface_id": "0",
          "frame.interface_id_tree": {
            "frame.interface_name": "any"
          },
          "frame.encap_type": "25",
          "frame.time": "Nov 25, 2023 11:06:45.466914320 CET",
          "frame.offset_shift": "0.000000000",
          "frame.time_epoch": "1700906805.466914320",
          "frame.time_delta": "0.000000000",
          "frame.time_delta_displayed": "0.000000000",
          "frame.time_relative": "38.431419126",
          "frame.number": "8324",
          "frame.len": "92",
          "frame.cap_len": "92",
          "frame.marked": "0",
          "frame.ignored": "0",
          "frame.protocols": "sll:ethertype:ip:udp:snmp"
        },
        "sll": {
          "sll.pkttype": "0",
          "sll.hatype": "1",
          "sll.halen": "6",
          "sll.src.eth": "02:42:ac:13:00:03",
          "sll.unused": "06:0b",
          "sll.etype": "0x0800"
        },
        "ip": {
          "ip.version": "4",
          "ip.hdr_len": "20",
          "ip.dsfield": "0x00",
          "ip.dsfield_tree": {
            "ip.dsfield.dscp": "0",
            "ip.dsfield.ecn": "0"
          },
          "ip.len": "76",
          "ip.id": "0xdb3b",
          "ip.flags": "0x40",
          "ip.flags_tree": {
            "ip.flags.rb": "0",
            "ip.flags.df": "1",
            "ip.flags.mf": "0"
          },
          "ip.frag_offset": "0",
          "ip.ttl": "64",
          "ip.proto": "17",
          "ip.checksum": "0xe8a5",
          "ip.checksum.status": "2",
          "ip.src": "172.19.0.3",
          "ip.addr": "172.19.0.3",
          "ip.src_host": "172.19.0.3",
          "ip.host": "172.19.0.3",
          "ip.dst": "192.168.10.1",
          "ip.addr": "192.168.10.1",
          "ip.dst_host": "192.168.10.1",
          "ip.host": "192.168.10.1"
        },
        "udp": {
          "udp.srcport": "33364",
          "udp.dstport": "161",
          "udp.port": "33364",
          "udp.port": "161",
          "udp.length": "56",
          "udp.checksum": "0x7709",
          "udp.checksum.status": "2",
          "udp.stream": "170",
          "Timestamps": {
            "udp.time_relative": "1.449620829",
            "udp.time_delta": "0.000000000"
          },
          "udp.payload": "30:2e:02:01:01:04:08:73:33:63:75:72:31:37:79:a5:1f:02:04:6f:9d:5d:81:02:01:00:02:01:0a:30:11:30:0f:06:0b:2b:06:01:02:01:1f:01:01:01:11:0a:05:00"
        },
        "snmp": {
          "snmp.version": "1",
          "snmp.community": "public",
          "snmp.data": "5",
          "snmp.data_tree": {
            "snmp.getBulkRequest_element": {
              "snmp.request_id": "1872584065",
              "snmp.non_repeaters": "0",
              "snmp.max_repetitions": "10",
              "snmp.variable_bindings": "1",
              "snmp.variable_bindings_tree": {
                "1.3.6.1.2.1.31.1.1.1.17.10: Value (Null)": {
                  "snmp.name": "1.3.6.1.2.1.31.1.1.1.17.10",
                  "snmp.value.null": ""
                }
              }
            }
          }
        }
      }
    }
  }
  ```

**Comment by indigo423** [comment]
Closing as almost certainly resolved: this report targets the pre-0.1.0 stack (Elasticsearch config, `RIPTIDE_SNMP_CONFIG_DEFINITIONS` env shape — both gone). The SNMP path was fully rebuilt for v0.1.0: node-model config (`riptide.nodes.<name>`), SNMP4J 3.12 with the post-build builder fix, credential references, and hardened interface resolution — and **v2c enrichment is continuously exercised in CI**: the full-mode e2e walks SNMP v2c back to simulated agents on every PR. If you can still reproduce against `riptide:0.1.0`, please reopen with the new config shape and the exception.
