### ISSUE TITLE
🐞 Nullpointer exception on flow enrichment

### ISSUE THREAD

**Issue by indigo423** [Riptide-Labs/riptide#68]
When I try to run the riptide service with 
```
  riptide:
    image: quay.io/pikkalabs/riptide:latest
    environment:
      RIPTIDE_ELASTIC_URL: http://elastic-01.labmonkeys.tech:9200
```

I get a Null Pointer Exceptions on flow enrichment and nothing get's persisted to Elasticsearch.

```
riptide_1  | 2023-11-26T13:15:01.171Z  WARN 1 --- [pool-5-thread-4] org.riptide.flows.parser.ParserBase      : Error preparing records for dispatch.
riptide_1  |
riptide_1  | java.util.concurrent.CompletionException: java.lang.RuntimeException: org.riptide.pipeline.FlowException: Failed to enrich one or more flows.
riptide_1  | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
riptide_1  | Caused by: java.lang.RuntimeException: org.riptide.pipeline.FlowException: Failed to enrich one or more flows.
riptide_1  | 	at org.riptide.flows.Daemon.lambda$new$0(Daemon.java:42) ~[classes/:na]
riptide_1  | 	at org.riptide.flows.parser.ParserBase.lambda$transmit$1(ParserBase.java:158) ~[classes/:na]
riptide_1  | 	... 4 common frames omitted
riptide_1  | Caused by: org.riptide.pipeline.FlowException: Failed to enrich one or more flows.
riptide_1  | 	at org.riptide.pipeline.Pipeline.process(Pipeline.java:103) ~[classes/:na]
riptide_1  | 	at org.riptide.flows.Daemon.lambda$new$0(Daemon.java:39) ~[classes/:na]
riptide_1  | 	... 5 common frames omitted
riptide_1  | Caused by: java.lang.NullPointerException: Cannot invoke "org.riptide.classification.Protocol.getDecimal()" because the return value of "org.riptide.classification.ClassificationRequest.getProtocol()" is null
riptide_1  | 	at org.riptide.classification.internal.matcher.ProtocolMatcher.matches(ProtocolMatcher.java:23) ~[classes/:na]
riptide_1  | 	at org.riptide.classification.internal.decision.Classifier.classify(Classifier.java:83) ~[classes/:na]
riptide_1  | 	at org.riptide.classification.internal.decision.Tree.classify(Tree.java:244) ~[classes/:na]
riptide_1  | 	at org.riptide.classification.internal.DefaultClassificationEngine.classify(DefaultClassificationEngine.java:109) ~[classes/:na]
riptide_1  | 	at org.riptide.classification.internal.TimingClassificationEngine.classify(TimingClassificationEngine.java:29) ~[classes/:na]
riptide_1  | 	at org.riptide.classification.internal.AsyncReloadingClassificationEngine.classify(AsyncReloadingClassificationEngine.java:102) ~[classes/:na]
riptide_1  | 	at org.riptide.classification.ClassificationEnricher.enrich(ClassificationEnricher.java:33) ~[classes/:na]
riptide_1  | 	at org.riptide.pipeline.Enricher$Single.lambda$enrich$0(Enricher.java:24) ~[classes/:na]
riptide_1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[na:na]
riptide_1  | 	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[na:na]
riptide_1  | 	at org.riptide.pipeline.Enricher$Single.enrich(Enricher.java:25) ~[classes/:na]
riptide_1  | 	at org.riptide.pipeline.Pipeline.process(Pipeline.java:100) ~[classes/:na]
riptide_1  | 	... 6 common frames omitted
riptide_1  |
```

**Comment by indigo423** [comment]
Won't fix with removed Elasticsearch backend in #118
